defaults: &defaults
  working_directory: ~/react-init
  docker:
    - image: circleci/node:9.10
    - image: cypress/base:8

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
            - v1-deps-{{ .Branch }}
            - v1-deps
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          key: v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/.cache ## cache both yarn and Cypress!
      - persist_to_workspace:
          root: ./
          paths:
            - ./
  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ./
      - run: yarn test:cov
      - store_test_results:
          path: ./coverage
      - store_artifacts:
          path: ./coverage/lcov-report
          destination: coverage
      - run: $(yarn bin)/cypress run

  lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ./
      - run: yarn lint
  deploy:
    <<: *defaults
    steps:
      - checkout
      - run: echo 'DEPLOY_NOT_IMPLEMENTED'

workflows:
  version: 2
  workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - lint:
          requires:
            - build
      - deploy:
          requires:
            - test
            - lint
          filters:
            branches:
              only:
                - master
                - development
