defaults: &defaults
  working_directory: ~/react-init
  docker:
    - image: circleci/node:9.10

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-cache-{{ checksum "package.json" }}
            - v2-cache-
      - run: yarn
      - save_cache:
          paths:
            - node_modules
            - yarn.lock
          key: v2-cache-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: ./
          paths:
            - ./
  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ./
      - run: yarn validate
      - store_test_results:
          path: ./coverage
      - store_artifacts:
          path: ./coverage/lcov-report
          destination: coverage
  lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ./
      - run: yarn lint
  deploy:
    <<: *defaults
    steps:
      - checkout
      - run: echo 'DEPLOY_NOT_IMPLEMENTED'

workflows:
  version: 2
  workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - lint:
          requires:
            - build
      - deploy:
          requires:
            - test
            - lint
          filters:
            branches:
              only:
                - master
                - development
